# Generated by Django 5.0.7 on 2024-07-11 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Donneegroupeelectrogene',
            fields=[
                ('id_groupe', models.AutoField(db_column='ID_groupe', primary_key=True, serialize=False)),
                ('reason', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Reason', max_length=20, null=True)),
                ('date', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Date', max_length=15, null=True)),
                ('time', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Time', max_length=10, null=True)),
                ('mode', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Mode', max_length=4, null=True)),
                ('rpm', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='RPM', max_length=5, null=True)),
                ('pwr', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Pwr', max_length=4, null=True)),
                ('pf', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='PF', max_length=4, null=True)),
                ('gfrq', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Gfrq', max_length=5, null=True)),
                ('vg1', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Vg1', max_length=7, null=True)),
                ('vg2', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Vg2', max_length=7, null=True)),
                ('vg3', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Vg3', max_length=7, null=True)),
                ('il1', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='IL1', max_length=5, null=True)),
                ('il2', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='IL2', max_length=5, null=True)),
                ('il3', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='IL3', max_length=5, null=True)),
                ('ef', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='EF', max_length=4, null=True)),
                ('vm1', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Vm1', max_length=7, null=True)),
                ('vm2', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Vm2', max_length=7, null=True)),
                ('vm3', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Vm3', max_length=7, null=True)),
                ('mfrq', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Mfrq', max_length=4, null=True)),
                ('ubat', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='UBat', max_length=7, null=True)),
                ('oilp', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='OilP', max_length=10, null=True)),
                ('ai2', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='AI2', max_length=15, null=True)),
                ('ai3', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='AI3', max_length=20, null=True)),
                ('bin', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='BIN', max_length=30, null=True)),
                ('bout', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='BOUT', max_length=30, null=True)),
                ('bioe', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='BIOE', max_length=15, null=True)),
            ],
            options={
                'db_table': 'DonneegroupeElectrogene',
                'managed': False,
            },
        ),
    ]
