# Generated by Django 5.0.7 on 2024-07-11 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groupeElectrogene', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='donneegroupeelectrogene',
            options={},
        ),
    ]
